### ISSUE TITLE
Allow for opening files via command line

### ISSUE THREAD

**Issue by ghost** [minodisk/markn#12]
Please allow me to open files like this:

`Markn This_is_a_Markdown_file.md` or `Markn -f This_is_a_Markdown_file.md`

**Comment by minodisk** [comment]
What OS do you use?

**Comment by ghost** [comment]
Linux Ubuntu

**Comment by minodisk** [comment]
I released new version: [v0.0.6](https://github.com/minodisk/markn/releases/tag/v0.0.6)

In my Ubuntu 15.04 amd64:

``` bash
wget https://github.com/minodisk/markn/releases/download/v0.0.6/Markn-linux-x64.zip
unzip Markn-linux-x64.zip
echo "# foo" > foo.md
./Markn-linux-x64/Markn foo.md
```

![2015-08-05 10 50 13](https://cloud.githubusercontent.com/assets/514164/9076618/d3aa22ce-3b5f-11e5-8da4-10f35ad428a4.png)

You may try it :wink:

**Comment by ghost** [comment]
Thank you! :+1: 

Now I can open files in the same directory. However I still am unable to open files that are not in the same directory:

`./Markn-linux-x64/Markn ~/Desktop/foo.md`

**Comment by minodisk** [comment]
Fix it in https://github.com/minodisk/markn/releases/tag/v0.0.7 :smile:

**Comment by xHN35RQ** [comment]
Works good! Thanks!

**Comment by ghost** [comment]
Works well! Thanks!
