### ISSUE TITLE
Add svg icon for linux

### ISSUE THREAD

**Issue by ghost** [minodisk/markn#14]
Do you have an svg version of the icon? If you do, I can provide a `Markn.desktop` file and install script to install the icon and launcher.

Thanks for this app it's looking very good!

**Comment by ghost** [comment]
Actually I figured out I can use the icons in the assets folder.

**Comment by minodisk** [comment]
Now I retouched it: https://github.com/minodisk/markn/blob/master/assets/icon.svg :metal:

**Comment by ghost** [comment]
bingo, you win! :dart: very nice!
