### ISSUE TITLE
Large space above first h1

### ISSUE THREAD

**Issue by ghost** [minodisk/markn#15]
There is a large empty space above the first `h1` as you can see my screenshot:

![foo1](https://cloud.githubusercontent.com/assets/9103375/9110361/f4ee535a-3bf1-11e5-8c09-a6ce152a7fa5.png)

The screenshot above feels like wasted space. It feels better for the spacing above first `h1` should be more like this so it's even with the side spacing:

![foo2](https://cloud.githubusercontent.com/assets/9103375/9110368/059c48a6-3bf2-11e5-946d-5b9fb442a728.png)

I tried to find the CSS to create a pull request for you, but could not find it.

This is just my opinion... I'm curious to hear what you think. Thanks!

**Comment by minodisk** [comment]
I think so too.
Fixed in [Release v0.0.9 · minodisk/markn](https://github.com/minodisk/markn/releases/tag/v0.0.9) :+1:

**Comment by ghost** [comment]
Thanks! :100:
