### ISSUE TITLE
On npm install, add link to /bin/Markn

### ISSUE THREAD

**Issue by ghost** [minodisk/markn#16]
On install, maybe add a link to the executable like so `node/bin/Markn` and this link points to the file in `node/lib/node_modules/markn/bin/Markn`

Most user put `node/bin/` in their path so they can run these npm packages on the command line. So they consider that an executable link should appear in that folder.

Thank you.

**Comment by xHN35RQ** [comment]
fixed, thank you! Works very good now. :smile_cat:

**Comment by ghost** [comment]
fixed, thank you! Works very good now. :smile_cat:

**Comment by minodisk** [comment]
Thanks for your trying :sushi::sushi:
