### ISSUE TITLE
Allow show images from local directory

### ISSUE THREAD

**Issue by ghost** [minodisk/markn#18]
Not sure if this has been fixed yet, but 0.0.9 can't show images loaded from same folder. Here's how vmd handles it: https://github.com/yoshuawuyts/vmd/blob/bc764bd589d7c31d8a25fd739b65c18bd6c39184/client.js#L9

**Comment by minodisk** [comment]
Implemented it in f63781fd8425a7523cd636025f188b2381b7e365 .
You may try https://github.com/minodisk/markn/releases/tag/v0.0.12 :metal:

**Comment by ghost** [comment]
Yes, it works! Good job :grinning:
