### ISSUE TITLE
regeneratorRuntime is not defined error

### ISSUE THREAD

**Issue by minhhh** [minodisk/markn#22]
Node version: 0.11.16
MacOS 10.10.5

Upon running `npm run debug` I encountered this error window: 

```
Uncaught Exception:
ReferenceError: regeneratorRuntime is not defined
    at Window.setTitle (/xxxx/markn/app/scripts/main.js:1000:15)
    at /xxxx/markn/app/scripts/main.js:973:14
    at /xxxx/markn/app/scripts/main.js:1359:10
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

Maybe it has something to do with babel config?

**Comment by minodisk** [comment]
Thanks for your reporting :sushi:
I tried to build after cleaning up my environment, the app throws same error.
Now I fixed it.

**Comment by minhhh** [comment]
It's working now. Thanks for fixing.
